DefaultContentLanguage = "en-US"
languageCode = "en-US"
title = "Gourmet Hiking"
baseurl = "http://gourmethiking.com/"
theme = "hugo-universal-theme"

# Define the number of posts per page
paginate = 10

# Enable comments by entering your Disqus shortname
disqusShortname = "gourmet-hiking"

# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-97048512-1"

[params]
	author = "Geneviève Masson"
	style = "default"
	copyright = "Copyright (c) 2017, Gourmet Hiking; all rights reserved."
	date_format = "January 2, 2006"
	#logo = "img/logo.png"

[[params.menu]]
    name = "Home"
    url  = "/"
    weight = 1

[[params.menu]]
    name = "Recipes"
    url  = "/recipes"
    weight = 2

[[params.menu]]
    name = "Product Reviews"
    url  = "/product-reviews"
    weight = 3

[[params.menu]]
    name = "Blog"
    url  = "/post"
    weight = 4

[[params.menu]]
    name = "About"
    url  = "/about"
    weight = 5

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"